language: go
notifications:
        email:
                recipients: dtherhtun.cw@gmail.com
                on_success: change
                on_failure: always
before_script:
- go get github.com/bmizerany/assert
